# Generated by Django 3.1.5 on 2021-01-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_district_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
