# Generated by Django 3.1.5 on 2021-03-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20210127_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='division',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.division'),
        ),
    ]
