# Generated by Django 3.1.5 on 2021-02-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
