# Generated by Django 3.1.5 on 2021-01-28 12:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='beds',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='dining',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='house',
            name='drawing',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='house',
            name='kitchen',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='house',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
