# Generated by Django 3.1.5 on 2021-01-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20210128_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='electricity_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='elevators',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='parking_space',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='service_elevator',
            field=models.BooleanField(default=False),
        ),
    ]
