# Generated by Django 3.1.5 on 2021-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20210128_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='elevators',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='parking_space',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
