# Generated by Django 3.1.5 on 2021-02-21 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20210128_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
