# Generated by Django 3.1.5 on 2021-02-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_house_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex')], default=('Apartment', 'Apartment'), max_length=15),
        ),
    ]
