# Generated by Django 3.1.5 on 2021-02-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20210222_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
