# Generated by Django 3.1.5 on 2021-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20210222_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Duplex', 'Duplex'), ('Triplex', 'Triplex')], default='Apartment', max_length=15),
        ),
    ]
