# Generated by Django 3.1.5 on 2021-03-16 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20210317_0147'),
        ('house', '0011_house_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rental.division'),
            preserve_default=False,
        ),
    ]
