# Generated by Django 3.1.5 on 2021-03-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20210317_0147'),
        ('house', '0012_auto_20210317_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.district'),
        ),
        migrations.AlterField(
            model_name='house',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.division'),
        ),
    ]
